- name: Run AndroidLint with reviewdog
  # You may pin to the exact commit or the version.
  # uses: DVDAndroid/action-android-lint@14f30f90a32a2c28b610d4b17a3246c100a27f01
  uses: DVDAndroid/action-android-lint@v1.2
  with:
    # GITHUB_TOKEN
    github_token: 
    # Path of Android Lint XML file
    lint_xml_file: 
    # Report level for reviewdog [info, warning, error]
    level: # optional, default is error
    # Reporter of reviewdog command [github-check, github-pr-check, github-pr-review].
Default is github-pr-check.

    reporter: # optional, default is github-check
    # Additional reviewdog flags
    reviewdog_flags: # optional, default is 
